name: psgc_update

recipe: laravel

config:
  webroot: ./public
  php: "8.2"
  database: postgres:14

services:
  appserver:
    scanner: false

  database:
    portforward: 33071
    creds:
      user: lhoopa
      password: password
      database: psgc

proxy:
  appserver:
    - psgc.localhost
